data:
  train_urls:
      - "gs://levanter-data/audio-data/train.txt"
  validation_urls:
      - "gs://levanter-data/audio-data/valid.txt"
  cache_dir: "gs://levanter-data/audio-data/dlwh-debug-cache/"
  tokenizer: "passthrough"
  plaintext: True
  enforce_eos: False
model:
  type: gpt2
  hidden_dim: 768
  num_heads: 12
  num_layers: 12
  seq_len: 8192
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
trainer:
  wandb:
    project: "levanter"
    tags: [ "audio", "gpt2"]
  mp: p=f32,c=bfloat16
  model_axis_size: 1
  per_device_parallelism: 2
  num_train_steps: 100000
  checkpointer:
    base_path: gs://levanter-data/audio-checkpoints/
  train_batch_size: 512
optimizer:
  learning_rate: 6E-4
  weight_decay: 0.1
  min_lr_ratio: 0.1
